name: birthday_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^3.0.3+6
  image_picker: ^1.1.2
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/image1.png
  - assets/image2.png
  - assets/image3.png
  - assets/music.mp3
  - assets/
